### ISSUE TITLE
Relative paths do not work

### ISSUE THREAD

**Issue by rubennorte** [seldo/nunjucks-hapi#7]
Templates extending or including other templates using relative paths (e.g.: `'./some/other/template'`) don't work because the wrapper isn't passing the filename to `Nunjucks.compile`.

[This line](https://github.com/seldo/nunjucks-hapi/blob/master/index.js#L14) should be replaced with:

```javascript
var template = Nunjucks.compile(src, env || options.environment, options.filename);
```

I was going to fix this in a fork, but I wasn't able to successfully run the tests in Windows, and I'm working with it now.

**Comment by seldo** [comment]
Fixed as https://github.com/seldo/nunjucks-hapi/commit/26e774027b2c1b2128e08c3efec66f005e610a3f

Thanks!

**Comment by rubennorte** [comment]
Still not working. In some cases (maybe all) the `filename` property of the `options` object is not own, making the code fail. I have to go back to my previous solution, assigning it directly from `options.filename` no matter what.

**Comment by rubennorte** [comment]
Knock knock?

**Comment by iammerrick** [comment]
Running into this same issue.
